---
# Here you can add variables that will be available for all hosts.
ansible_python_interpreter: "python3"

region: northeurope
resource_group: DIDA-ALRY23-DV1673-H25-LP2
domain_name: albinryberg.tech

admin_email: alry23@student.bth.se

vmtags:
    StudentId: alry23

pub_ssh_key_location: ssh_keys/keys.pub


server_user: "deploy"
server_user_pass: "DevOps2025!"
server_user_groups:
    -   sudo
