---
# Default variables for deploy_app_docker role

# Docker image configuration
app_docker_image: albinr/microblog
app_docker_tag: "{{ app_version | default('latest') }}"

# Container configuration
app_container_name: microblog-app
app_host_port: 8000
app_container_port: 5000

# Application run command
app_run_command: prod

# Container restart policy
app_restart_policy: always

db_host: database.albinryberg.tech
db_port: 3306
db_name: microblog
db_user: microblog
db_password: microblog_password
db_root_password: root_password
app_database_url: "mysql+pymysql://{{ db_user }}:{{ db_password }}@{{ db_host }}:{{ db_port }}/{{ db_name }}"